### ISSUE TITLE
Building ixgbe on Linux 5.7.8

### ISSUE THREAD

**Issue by joinsplit** [fabianishere/pve-edge-kernel#3] opened 2020-07-16 10:28 UTC
Hello,

After installing & using these latest kernels, I appear unable to update the ixgbe module (updating from default 5.1.0-k to 5.8.1):

`root@host:/tmp/ixgbe-5.8.1/src# make install
common.mk:82: *** Kernel header files not in any of the expected locations.
common.mk:83: *** Install the appropriate kernel development package, e.g.
common.mk:84: *** kernel-devel, for building kernel modules and try again.  Stop.`

Normally this seems to be a case of the headers not being installed correctly, but in the case of using these edge kernels, is there something missing or is there an additional package needed? I have installed:

linux-tools-5.7_5.7.8-1_amd64.deb
pve-edge-headers-5.7.8-1_5.7.8-1_amd64.deb
pve-edge-kernel-5.7.8-1-zen2_5.7.8-1_amd64.deb

`root@host:/usr/src# ls
linux-headers-5.3.13-3-pve  linux-headers-5.3.18-3-pve  linux-headers-5.4.41-1-pve  linux-headers-5.4.44-2-pve  linux-headers-5.6.8-1  linux-headers-5.7.8-1
linux-headers-5.3.18-2-pve  linux-headers-5.4.34-1-pve  linux-headers-5.4.44-1-pve  linux-headers-5.5.19-1      linux-headers-5.7.2-1`

Thanks for any assistance!

**Comment by fabianishere** [comment] 2020-07-16 10:36
Hi,

Where did you get the sources for ixgbe 5.8.1? I am trying to reproduce the issue, but I can currently only find up to version [5.7.1](https://downloadcenter.intel.com/download/29699/Intel-Network-Adapter-Driver-for-PCIe-Intel-10-Gigabit-Ethernet-Network-Connections-Under-Linux-?wapkw=ixgbe).

**Comment by fabianishere** [comment] 2020-07-16 10:42
Also, could you check the output of the following commands for me:
```bash
uname -r
```
and
```bash
ls /lib/modules/
```

**Comment by joinsplit** [comment] 2020-07-16 10:45
Hi,

Here is the sourceforge link:  https://sourceforge.net/projects/e1000/files/ixgbe%20stable/5.8.1/

`root@host:~# uname -r
5.7.8-1-zen2
`
`root@host:~# ls /lib/modules/
5.3.10-1-pve  5.3.18-2-pve  5.4.24-1-pve  5.4.34-1-pve  5.4.44-1-pve  5.5.19-1       5.6.8-1       5.7.2-1       5.7.8-1
5.3.13-3-pve  5.3.18-3-pve  5.4.27-1-pve  5.4.41-1-pve  5.4.44-2-pve  5.5.19-1-zen2  5.6.8-1-zen2  5.7.2-1-zen2  5.7.8-1-zen2
root@host:~#
`

**Comment by joinsplit** [comment] 2020-07-16 10:46
I do recall encountering this same issue with kernel 5.7.2 & ixgbe 5.7.1

**Comment by fabianishere** [comment] 2020-07-16 10:56
Okay, I think I have found the issue. You have installed the `5.7.8-1-zen2` kernel, but since I have only provided the headers for `5.7.8-1`, ixgbe rightfully complains that it cannot find the headers for `5.7.8-1-zen2`. A workaround right now would be to just install the generic `5.7.8-1` kernel.

I think I should not be adding the micro-architecture to the kernel version so that all kernels variants can share the same header package.

**Comment by joinsplit** [comment] 2020-07-16 11:03
Ok that makes sense - are there performance improvements to be gained from the zen2 version? I'll revert to the generic version in any case, thanks for finding the issue.

**Comment by fabianishere** [comment] 2020-07-16 11:10
I haven't measured it, but to be honest (and from what I have read) I don't really think it matters that much for the Linux kernel. I just wanted to test this functionality :P

**Comment by joinsplit** [comment] 2020-07-16 11:32
I guess i was just too tempted by an edge kernel tailored to my microarchitecture :)
5.7.8-1 installed & its all working as expected, thanks again!

**Comment by fabianishere** [comment] 2020-08-09 12:44
This should be fixed now.

**Closed** 2020-08-09 12:44 UTC
Labels: question
