### ISSUE TITLE
slow Network with e1000 Intel

### ISSUE THREAD

**Issue by beroliv** [fabianishere/pve-edge-kernel#221] opened 2022-01-05 16:04 UTC
Hello,
some network Cards are Problems with the current Kernel. is it possible to fix it with?
Look at this Treads also pls
Workaround with Kernel Parameters. 

`GRUB_CMDLINE_LINUX_DEFAULT="quiet intel_idle.max_cstate=1"`

https://forum.proxmox.com/threads/langsame-verbindung-ins-wan-im-lan-alles-gut.100500/
https://forum.proxmox.com/threads/slow-internet-speed-on-pve-but-not-on-local-network.99514/
https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1927925

**Comment by fabianishere** [comment] 2022-01-05 20:05
The patches provided in that issue are already included in Linux 5.15: https://github.com/gregkh/linux/commit/639e298f432fb058a9496ea16863f53b1ce935fe

**Comment by beroliv** [comment] 2022-01-05 20:12
i have actually 5.15.7-1-pve Kernel installed and still the slow network if i boot with out Kernel Parameter. Should i try your 15.5 Edge Kernel?

**Comment by fabianishere** [comment] 2022-01-05 20:14
I recommend at least trying to see whether 5.15.12-1 fixes your issues. Otherwise, you are facing another issue than the one described in the Ubuntu issue.

**Comment by beroliv** [comment] 2022-01-05 20:16
give me a moment pls

**Comment by beroliv** [comment] 2022-01-05 20:35
Well, looks good so far :-) let my speed Tracker check the line this night - actually i reach close 500Mbit from 600Mbit. But much better than with the bug. (20Mbit around)
Do you have a Link from the Ubuntu issue?

**Comment by fabianishere** [comment] 2022-01-05 20:36
It is the one you referenced.

**Comment by beroliv** [comment] 2022-01-05 20:38
what is the reason you have your own build Kernel?. Whats the different?. i miss that in the description

**Comment by fabianishere** [comment] 2022-01-05 20:53
Usually, Proxmox lags a bit behind from the mainline Linux kernel, so I'll build a compatible kernel based on the latest Linux stable version. Coincidentally, Proxmox has recently started building a Linux 5.15 kernel themselves. However, Linux 5.16 will be released soon, so then I'll be ahead again.

**Comment by beroliv** [comment] 2022-01-05 20:54
super -  thank you for your great effort! Dutch Quality!!

**Comment by lolekuk** [comment] 2022-01-05 21:36
Hi @fabianishere  and @beroliv,

I have been using edge kernels for quite a few weeks now (hoping it would fix my network problem on Intel NIC) and it still wasn't working on the 5.15 kernel until I've added today to kernel parameters line: 
`GRUB_CMDLINE_LINUX_DEFAULT="quiet intel_idle.max_cstate=1"`

It's working now.

Hope this helps.

Thanks and great work 👍

**Comment by beroliv** [comment] 2022-01-05 21:38
the idea is to have kernel running how dont need a workaround. Everything should work out of the box

**Comment by fabianishere** [comment] 2022-02-06 17:09
Closing this issue, since it is not related to this project, but probably a kernel regression.

**Closed by fabianishere** 2022-02-06 17:09 UTC
Labels: bug
